version: "3"
services:
    api:
        build: .
        ports:
            - "9000:9000"
        depends_on:
            - db
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: "parktrack"